// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD8fQyTiM9uG3gyCwYy_l46PsDc7EcQHw',
    appId: '1:877494086901:web:b6d2866c7733bbd50ae9bc',
    messagingSenderId: '877494086901',
    projectId: 'barcodbek',
    authDomain: 'barcodbek.firebaseapp.com',
    storageBucket: 'barcodbek.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo3jsrJB0U9aqoYXUkisVn-MMhm6TFlMI',
    appId: '1:877494086901:android:a0bc8c64a60696fb0ae9bc',
    messagingSenderId: '877494086901',
    projectId: 'barcodbek',
    storageBucket: 'barcodbek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIcFo-bfkEcpIVfsgIJhMiRGmozfrxlAg',
    appId: '1:877494086901:ios:85efa073b8891f3f0ae9bc',
    messagingSenderId: '877494086901',
    projectId: 'barcodbek',
    storageBucket: 'barcodbek.appspot.com',
    iosBundleId: 'com.example.barcodbek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIcFo-bfkEcpIVfsgIJhMiRGmozfrxlAg',
    appId: '1:877494086901:ios:4def469def6a50e30ae9bc',
    messagingSenderId: '877494086901',
    projectId: 'barcodbek',
    storageBucket: 'barcodbek.appspot.com',
    iosBundleId: 'com.example.barcodbek.RunnerTests',
  );
}
